version: '3.7'
services:
  web:
    image: flaskapp:demo
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:12345678@db/flaskmysql

    ports:
    - published: 5000
      target: 5000
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: flaskmysql
volumes:
  mysql-data: